### ISSUE TITLE
./configure: No such file or directory

### ISSUE THREAD

**Issue by leonorrib** [ViennaRNA/RNAcode#11]
Dear RNAcode team,

I am trying to install RNAcode but in the very first step it tells me that there is no configure file. And indeed there is no such file. There is a file called "configure.ac" instead. I also tried running the "autogen.sh" script, but that doesn't work either. It stays running forever. Do you know a solution for that?

Best,
Leonor

**Comment by leonorrib** [comment]
I could manage to solve it by myself. In case the way I did it helps someone else here I am posting what I did. The current version on github doesn't have the necessary files to make the installation, but I managed to install another version (perhaps older, not sure). I could donwload it from: http://github.com/downloads/wash/rnacode/RNAcode-0.3.tar.gz

tar -xzf RNAcode-0.3.tar.gz
./configure
make
make install (requires root privileges)

# If you don't have root privileges you can also run:

./configure --prefix=/path_to_your_tool_directory

Best,
Leonor

**Comment by svenderheld** [comment]
Dear Leonor,

this "old" version should be OK as well. So far there was no other version released. However, if you clone the repository, run autogen.sh (Sorry, this is missing in the README.md) and subsequently configure and make it should work. If not we would appreciate more details about your OS and other important configuration aspects that might help to get rid of this issue.

Best,
Sven

Step by step system calls:

git clone https://github.com/ViennaRNA/RNAcode.git
cd RNAcode/
./autogen.sh
./configure OR ./configure --prefix=/path_to_your_tool_directory
make
make install
