### ISSUE TITLE
How to understand the result of RNAcode

### ISSUE THREAD

**Issue by li0604** [ViennaRNA/RNAcode#12]
Dear professor,

I have test this software and got the results. Details showed as follwing:

The input file:
#test_file.ffn
>k10_contig_16766_fa_2_ffn
ATGGATTATATTATTAGTATACCGATGGAAGATGGAGAAGACGAAGAATTGTGTTTCCCAGATACCGAAAATATGTACGGATTTTTAGCATTACTTATGGAATCTGGAAAAGACATTTCAGACATTATTATCCCAGAGGGAGGATTAGTATGA
>k21_contig_1018318_fa_2_ffn
ATGGATTATATTATTAGTATACCGATGGAAGACGGAGAAGACGAAGAGTTGTGTTTTCCAGATACAGAAAATATGTACGGATTTTTGGATTTACTTTCCGAAAGTGGTAAAGATATTTCAGAAATTATTATCCCAGAGGGCGGATTAGTATGA
>k7_contig_499132_fa_2_ffn
ATGGATTATATTATTAGTATACCGATGGAAGACGGAGAAGACGAAGAATTGTGTTTCCCAGATACCGAAAATATGTACGGATTTTTAGCTTTGCTTATGGAATCTGGAAAAGACATTTCAGATATTATTATCCCAGAGGGAGGATTAGTATGA
>Ph6_contig_121989_fa_2_ffn
ATGGATTATATTATTAGTATACCGATGGAAGACGGAGAAGACGAAGAATTGTGTTTCCCAGATACCGAAAATATGTACGGATTTTTAGATTTACTTTCTGAATCTGGTAAAGATATTTCAGAAATTATTATACCAGAAGGCGGATTAGTATGA

the command I used:
#for alignment
clustalw2 test_file.ffn

#for RNAcode
RNAcode  test_file.aln --outfile test_file_results.gtf --gtf --best-only --cutoff 0.05 

the results 
#clustalw2
**test_file.dnd** 
`(
(
k10_contig_16766_fa_2_ffn:0.01634,
k7_contig_499132_fa_2_ffn:0.00980)
:0.04575,
k21_contig_1018318_fa_2_ffn:0.04248,
Ph6_contig_121989_fa_2_ffn:0.01634);
`

**test_file.aln**
`CLUSTAL 2.1 multiple sequence alignment

k21_contig_1018318_fa_2_ffn      ATGGATTATATTATTAGTATACCGATGGAAGACGGAGAAGACGAAGAGTT
Ph6_contig_121989_fa_2_ffn       ATGGATTATATTATTAGTATACCGATGGAAGACGGAGAAGACGAAGAATT
k10_contig_16766_fa_2_ffn        ATGGATTATATTATTAGTATACCGATGGAAGATGGAGAAGACGAAGAATT
k7_contig_499132_fa_2_ffn        ATGGATTATATTATTAGTATACCGATGGAAGACGGAGAAGACGAAGAATT
                                 ******************************** ************** **

k21_contig_1018318_fa_2_ffn      GTGTTTTCCAGATACAGAAAATATGTACGGATTTTTGGATTTACTTTCCG
Ph6_contig_121989_fa_2_ffn       GTGTTTCCCAGATACCGAAAATATGTACGGATTTTTAGATTTACTTTCTG
k10_contig_16766_fa_2_ffn        GTGTTTCCCAGATACCGAAAATATGTACGGATTTTTAGCATTACTTATGG
k7_contig_499132_fa_2_ffn        GTGTTTCCCAGATACCGAAAATATGTACGGATTTTTAGCTTTGCTTATGG
                                 ****** ******** ******************** *  ** ***   *

k21_contig_1018318_fa_2_ffn      AAAGTGGTAAAGATATTTCAGAAATTATTATCCCAGAGGGCGGATTAGTA
Ph6_contig_121989_fa_2_ffn       AATCTGGTAAAGATATTTCAGAAATTATTATACCAGAAGGCGGATTAGTA
k10_contig_16766_fa_2_ffn        AATCTGGAAAAGACATTTCAGACATTATTATCCCAGAGGGAGGATTAGTA
k7_contig_499132_fa_2_ffn        AATCTGGAAAAGACATTTCAGATATTATTATCCCAGAGGGAGGATTAGTA
                                 **  *** ***** ******** ******** ***** ** *********

k21_contig_1018318_fa_2_ffn      TGA
Ph6_contig_121989_fa_2_ffn       TGA
k10_contig_16766_fa_2_ffn        TGA
k7_contig_499132_fa_2_ffn        TGA
                                 ***
`

#RNAcode
`k21_contig_1018318_fa_2_ffn	RNAcode	CDS	2	154	37.78|2.19e-04	+	.	gene_id "Gene0"; transcript_id "transcript 0";
`

I am confused that the result indicated k21_contig_1018318_fa_2_ffn is conding sequence? Other three sequences are not ?

Thanks a lot.

**Comment by svenderheld** [comment]
It seems that your input is somehow broken because it creates serval aligned blocks and not just one alignment containing the four sequences named k10_contig_16766_fa_2_ffn, k7_contig_499132_fa_2_ffn, k21_contig_1018318_fa_2_ffn and Ph6_contig_121989_fa_2_ffn. If I'm right you want to ask if an alignment created with clustalw2 based on these four sequences of 153 nt length has coding potential or not. I created a valid fasta file from your input and compeled the analysis you describe. Please see the results at www.bioinf.uni-leipzig.de/~sven/files/rnacode_issue12.tar.gz 

I hope this helps?

Best,
Sven

**Comment by li0604** [comment]
Thanks for your e-mail and your patience. 

Yes, you are right. I want to know if an alignment created with clustalw2 based on these four sequences of 153 nt length has coding potential or not. 
The same sequence was predicted as coding ORF but with differen p-value according our results.

**Comment by li0604** [comment]
Dear perfessor,


Thanks for your e-mail and your patience. 


Yes, you are right. I want to know if an alignment created with clustalw2 based on these four sequences of 153 nt length has coding potential or not. 


We got the same sequence predicted as coding ORF but with different p-value.


Because of these four sequences cd-hit into the same cluster.I want to know this cluster can be used for further analysis.


Thanks a lot.


Yours sincerely,
Qingmei Li















At 2021-11-24 23:53:10, "Sven Findeiß" ***@***.***> wrote:

It seems that your input is somehow broken because it creates serval aligned blocks and not just one alignment containing the four sequences named k10_contig_16766_fa_2_ffn, k7_contig_499132_fa_2_ffn, k21_contig_1018318_fa_2_ffn and Ph6_contig_121989_fa_2_ffn. If I'm right you want to ask if an alignment created with clustalw2 based on these four sequences of 153 nt length has coding potential or not. I created a valid fasta file from your input and compeled the analysis you describe. Please see the results at www.bioinf.uni-leipzig.de/~sven/files/rnacode_issue12.tar.gz

I hope this helps?

Best,
Sven

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
