### ISSUE TITLE
Missing git tags for recent release(s)

### ISSUE THREAD

**Issue by peterjc** [ViennaRNA/RNAcode#6]
Currently I only see git tags `Pre1` and `0.2-beta`.

Which source code went into the 0.3 release?
http://github.com/downloads/wash/rnacode/RNAcode-0.3.tar.gz

**Comment by Lfulcrum** [comment]
Coming to this 9 years later, I'm still looking for a `0.3` tag 🥲

**Comment by peterjc** [comment]
The website https://viennarna.github.io/RNAcode/ still has the (now broken) link to http://github.com/downloads/wash/rnacode/RNAcode-0.3.tar.gz

Note https://github.com/wash/rnacode redirects to https://github.com/ViennaRNA/RNAcode but that tar-ball link does not.

**Comment by Lfulcrum** [comment]
This makes me sad 😭 

It's obviously quite important for reproducibility to know which version of code has been used for a particular version. Biocontainer docker images have been made for version `0.3` (https://quay.io/repository/biocontainers/rnacode?tab=tags), but I'm not certain what code has actually been used for these (I suppose the `master` branch).

**Comment by peterjc** [comment]
Yes, that's similar to why I was asking (although I forget the exact circumstances now).

Outsiders to the project could at best make a good guess from the approximate time of the 0.3 "release" via the website (and linked events like when docker images where made from it), and narrow it down to a likely range of commits on the master branch.

**Comment by svenderheld** [comment]
Thanks for trying again! We went back in time and tested the version from a couple years ago when wash had changed the version information in the configure.ac file. 

This is now available as tag v0.3, which should also match the version that was previously available at [1].

Recent changes are tagged v0.3.1 and a release of this is now available on github.

We apologize for the inconvenience.

Yours sincerely,
Sven

[1] http://github.com/downloads/wash/rnacode/RNAcode-0.3.tar.gz

**Comment by Lfulcrum** [comment]
Hi @svenderheld,

No worries at all - this is great news! Thanks very much for looking into this and generating tags for us 🤩 You have removed my fear of non-reproducibility.

**Comment by peterjc** [comment]
Excellent, thank you! I'm going to mark this issue as resolved 👍
